Repository Titubeobear/TBB_FE, pull requests merged in 2022-12, with the labels that each got.

#7 Feat: eslint prettier lefthook 설정
  .eslintrc.js
  .prettierrc
  lefthook.yml
  package.json
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  yarn.lock
Labels: 💡 feature

#8 Feature/#5 githubaction
  .github/actions/yarn-install/action.yml
  .github/workflows/ci-tbb-app.yml
Labels: 💡 feature

#9 Develop
  .eslintrc.js
  .github/actions/yarn-install/action.yml
  .github/workflows/ci-tbb-app.yml
  .prettierrc
  lefthook.yml
  package.json
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  yarn.lock
Labels: 💪 enhancement, 💡 feature

#10 Test: git action test
  src/App.tsx
Labels: 💡 feature

#11 Develop
  src/App.tsx
Labels: 💡 feature

#13 [Feat] gh-pages 설치
  package.json
  yarn.lock
Labels: 💡 feature

#14 Fix: github action pages 연동 시킴
  .github/workflows/ci-tbb-app.yml
Labels: 💡 feature

#15 Develop
  .github/workflows/ci-tbb-app.yml
Labels: duplicate, 💡 feature

#17 Feat: permission 삭제
  .github/workflows/ci-tbb-app.yml
Labels: 🐛 bug

#18 Fix: publish_dir ./build로 변경
  .github/workflows/ci-tbb-app.yml
Labels: 🐛 bug
